// SPAWN NAME FOR OVERALL REFERENCE IN MODULES
module.exports.SP2_NAME = 'SP2';

// CREEP TYPE SPAWN LIMITS
module.exports.HARVESTER_LIMIT = 0;
module.exports.BUILDER_LIMIT = 3;
module.exports.UPGRADER_LIMIT = 3;
module.exports.REPAIRER_LIMIT = 0;
module.exports.TRANSPORTER_LIMIT = 1;
module.exports.DEDICATED_HARVESTER1_LIMIT = 1;
module.exports.DEDICATED_HARVESTER0_LIMIT = 0;

// TICKS LEFT IN CREEP'S LIFE BEFORE IT'S CONSIDERED USELESS (RETURN FOR FINAL TASK AND WAIT TO DIE!)
module.exports.TICKS_LEFT = 50;

// HITPOINTS LEFT IN A STRUCTURE BEFORE REPAIR CREEPS ARE CALLED IN FOR THE RESCUE (IN PERCENTAGE OF MAX HIT POINTS)
module.exports.REPAIR_THRESHOLD = 0.5;